### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by MayaJava** [jblattgerste/sus-analysis-toolkit#5]
Hello Dear,
Thank you for this very important toolkit. When i upload my data, all seem good except the colors of results by questions, where it keeps giving red color for a question where no "strongly disagree" result was there for all participants. There were just neutral-agree-strongly agree for this question as results. colors given in the chart are for strongly disagree-disagree- neutral. knowing that's the first question and it is positive one.
thank you
Kind regards
Maryam

**Comment by jblattgerste** [comment]
Hello Maryam,

You are welcome, we are happy if it helps people!

"Colors of results by questions" was indeed a bug in the published version. Thank you for pointing this out.

Firstly, there was a small bug where data for this specific plot was not calculated correctly. Secondly, the option to choose the type of coloring was confusing to begin with. In an internal discussion, we decided to remove the option and always use "color by meaning" by default.

We published a major update to the SUS Analysis Toolkit yesterday, where this bug should also be fixed: https://sus.mixality.de/

And will shortly pull the changes into this repository.
