### ISSUE TITLE
[Request] New Plot Type

### ISSUE THREAD

**Issue by sraedler** [jblattgerste/sus-analysis-toolkit#8]
First of all, thank you for the web toolkit. This is very helpful!

May I ask to add an additional plot type selection?
It is a mixture of the plot types "Preset 3" and "Preset 1".

Particularly, I would like to have the percentile value of preset 3 and the spider matrix of preset 1.

If this is not possible in a short 

Thank you very much!

**Comment by jblattgerste** [comment]
Hi @sraedler ,

We are happy if it helps, and thank you for the feedback/suggestion!

This is certainly a good suggestion, and we are planning to provide more freedom to the user in the single-study dashboard (e.g. choosing which combination of visualizations the user wants to use, so you could decide yourself). But as I am currently in the writing phase of my PhD thesis and @jan-behrends just started a new job, a new release will probably be worked on toward the end of this year.

In the meantime, as a workaround: Maybe you can export the chart in both versions and then overlay them with Paint or another photo editor?

Hope that helps!

**Comment by jblattgerste** [comment]
This feature request would be covered through #12
